/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const Generic_partsIndexLazyRouteImport = createFileRoute('/generic_parts/')()
const InquiriesIndexLazyRouteImport = createFileRoute('/inquiries/')()
const InventoryIndexLazyRouteImport = createFileRoute('/inventory/')()
const Inventory_categoriesIndexLazyRouteImport = createFileRoute(
  '/inventory_categories/',
)()
const Service_templatesIndexLazyRouteImport = createFileRoute(
  '/service_templates/',
)()
const Units_of_measureIndexLazyRouteImport =
  createFileRoute('/units_of_measure/')()
const Service_templatesIdIndexLazyRouteImport = createFileRoute(
  '/service_templates/$id/',
)()
const Service_templatesNewIndexLazyRouteImport = createFileRoute(
  '/service_templates/new/',
)()

const Generic_partsIndexLazyRoute = Generic_partsIndexLazyRouteImport.update({
  id: '/generic_parts/',
  path: '/generic_parts/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/generic_parts/index.lazy').then((d) => d.Route),
)
const InquiriesIndexLazyRoute = InquiriesIndexLazyRouteImport.update({
  id: '/inquiries/',
  path: '/inquiries/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/inquiries/index.lazy').then((d) => d.Route),
)
const InventoryIndexLazyRoute = InventoryIndexLazyRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/inventory/index.lazy').then((d) => d.Route),
)
const Inventory_categoriesIndexLazyRoute =
  Inventory_categoriesIndexLazyRouteImport.update({
    id: '/inventory_categories/',
    path: '/inventory_categories/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/inventory_categories/index.lazy').then((d) => d.Route),
  )
const Service_templatesIndexLazyRoute =
  Service_templatesIndexLazyRouteImport.update({
    id: '/service_templates/',
    path: '/service_templates/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/service_templates/index.lazy').then((d) => d.Route),
  )
const Units_of_measureIndexLazyRoute =
  Units_of_measureIndexLazyRouteImport.update({
    id: '/units_of_measure/',
    path: '/units_of_measure/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/units_of_measure/index.lazy').then((d) => d.Route),
  )
const Service_templatesIdIndexLazyRoute =
  Service_templatesIdIndexLazyRouteImport.update({
    id: '/service_templates/$id/',
    path: '/service_templates/$id/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/service_templates/$id/index.lazy').then((d) => d.Route),
  )
const Service_templatesNewIndexLazyRoute =
  Service_templatesNewIndexLazyRouteImport.update({
    id: '/service_templates/new/',
    path: '/service_templates/new/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/service_templates/new/index.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/generic_parts/': typeof Generic_partsIndexLazyRoute
  '/inquiries/': typeof InquiriesIndexLazyRoute
  '/inventory/': typeof InventoryIndexLazyRoute
  '/inventory_categories/': typeof Inventory_categoriesIndexLazyRoute
  '/service_templates/': typeof Service_templatesIndexLazyRoute
  '/units_of_measure/': typeof Units_of_measureIndexLazyRoute
  '/service_templates/$id/': typeof Service_templatesIdIndexLazyRoute
  '/service_templates/new/': typeof Service_templatesNewIndexLazyRoute
}
export interface FileRoutesByTo {
  '/generic_parts': typeof Generic_partsIndexLazyRoute
  '/inquiries': typeof InquiriesIndexLazyRoute
  '/inventory': typeof InventoryIndexLazyRoute
  '/inventory_categories': typeof Inventory_categoriesIndexLazyRoute
  '/service_templates': typeof Service_templatesIndexLazyRoute
  '/units_of_measure': typeof Units_of_measureIndexLazyRoute
  '/service_templates/$id': typeof Service_templatesIdIndexLazyRoute
  '/service_templates/new': typeof Service_templatesNewIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/generic_parts/': typeof Generic_partsIndexLazyRoute
  '/inquiries/': typeof InquiriesIndexLazyRoute
  '/inventory/': typeof InventoryIndexLazyRoute
  '/inventory_categories/': typeof Inventory_categoriesIndexLazyRoute
  '/service_templates/': typeof Service_templatesIndexLazyRoute
  '/units_of_measure/': typeof Units_of_measureIndexLazyRoute
  '/service_templates/$id/': typeof Service_templatesIdIndexLazyRoute
  '/service_templates/new/': typeof Service_templatesNewIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/generic_parts/'
    | '/inquiries/'
    | '/inventory/'
    | '/inventory_categories/'
    | '/service_templates/'
    | '/units_of_measure/'
    | '/service_templates/$id/'
    | '/service_templates/new/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/generic_parts'
    | '/inquiries'
    | '/inventory'
    | '/inventory_categories'
    | '/service_templates'
    | '/units_of_measure'
    | '/service_templates/$id'
    | '/service_templates/new'
  id:
    | '__root__'
    | '/generic_parts/'
    | '/inquiries/'
    | '/inventory/'
    | '/inventory_categories/'
    | '/service_templates/'
    | '/units_of_measure/'
    | '/service_templates/$id/'
    | '/service_templates/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Generic_partsIndexLazyRoute: typeof Generic_partsIndexLazyRoute
  InquiriesIndexLazyRoute: typeof InquiriesIndexLazyRoute
  InventoryIndexLazyRoute: typeof InventoryIndexLazyRoute
  Inventory_categoriesIndexLazyRoute: typeof Inventory_categoriesIndexLazyRoute
  Service_templatesIndexLazyRoute: typeof Service_templatesIndexLazyRoute
  Units_of_measureIndexLazyRoute: typeof Units_of_measureIndexLazyRoute
  Service_templatesIdIndexLazyRoute: typeof Service_templatesIdIndexLazyRoute
  Service_templatesNewIndexLazyRoute: typeof Service_templatesNewIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/generic_parts/': {
      id: '/generic_parts/'
      path: '/generic_parts'
      fullPath: '/generic_parts/'
      preLoaderRoute: typeof Generic_partsIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inquiries/': {
      id: '/inquiries/'
      path: '/inquiries'
      fullPath: '/inquiries/'
      preLoaderRoute: typeof InquiriesIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory_categories/': {
      id: '/inventory_categories/'
      path: '/inventory_categories'
      fullPath: '/inventory_categories/'
      preLoaderRoute: typeof Inventory_categoriesIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service_templates/': {
      id: '/service_templates/'
      path: '/service_templates'
      fullPath: '/service_templates/'
      preLoaderRoute: typeof Service_templatesIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/units_of_measure/': {
      id: '/units_of_measure/'
      path: '/units_of_measure'
      fullPath: '/units_of_measure/'
      preLoaderRoute: typeof Units_of_measureIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service_templates/$id/': {
      id: '/service_templates/$id/'
      path: '/service_templates/$id'
      fullPath: '/service_templates/$id/'
      preLoaderRoute: typeof Service_templatesIdIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service_templates/new/': {
      id: '/service_templates/new/'
      path: '/service_templates/new'
      fullPath: '/service_templates/new/'
      preLoaderRoute: typeof Service_templatesNewIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  Generic_partsIndexLazyRoute: Generic_partsIndexLazyRoute,
  InquiriesIndexLazyRoute: InquiriesIndexLazyRoute,
  InventoryIndexLazyRoute: InventoryIndexLazyRoute,
  Inventory_categoriesIndexLazyRoute: Inventory_categoriesIndexLazyRoute,
  Service_templatesIndexLazyRoute: Service_templatesIndexLazyRoute,
  Units_of_measureIndexLazyRoute: Units_of_measureIndexLazyRoute,
  Service_templatesIdIndexLazyRoute: Service_templatesIdIndexLazyRoute,
  Service_templatesNewIndexLazyRoute: Service_templatesNewIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
