/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const InquiriesIndexLazyRouteImport = createFileRoute('/inquiries/')()

const InquiriesIndexLazyRoute = InquiriesIndexLazyRouteImport.update({
  id: '/inquiries/',
  path: '/inquiries/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/inquiries/index.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/inquiries/': typeof InquiriesIndexLazyRoute
}
export interface FileRoutesByTo {
  '/inquiries': typeof InquiriesIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/inquiries/': typeof InquiriesIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/inquiries/'
  fileRoutesByTo: FileRoutesByTo
  to: '/inquiries'
  id: '__root__' | '/inquiries/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  InquiriesIndexLazyRoute: typeof InquiriesIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/inquiries/': {
      id: '/inquiries/'
      path: '/inquiries'
      fullPath: '/inquiries/'
      preLoaderRoute: typeof InquiriesIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  InquiriesIndexLazyRoute: InquiriesIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
